<?php

namespace AppBundle\Repository;

/**
 * ThanksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThanksRepository extends \Doctrine\ORM\EntityRepository
{
}
